### GET http://localhost:5000/
GET http://127.0.0.1:3000/


### POST on Auth sign up feature 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "bryanli@temple.edu",
  "password": "1234567",
  "username": "hello_user"
}

### POST login user not confirmed email
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "bryanli@temple.edu",
  "password": "1234567"
}



### POST login user confirmed email
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "hello@gmail.com",
  "password": "1234567"
}

###GET Sign out
POST  http://localhost:3000/auth/logout
Content-Type: application/json


###Get user session
GET http://localhost:3000/auth/get_user